
const fs = require("fs");
let html = fs.readFileSync("index.html", "utf8");
const R = "\uFFFD";
const map = {
  ["ABRIGO ESPERAN" + R + "A"]: "ABRIGO ESPERANÇA",
  ["NAVEGA" + R + "!ÒO"]: "NAVEGAÇÃO",
  ["HIST" + R + " RIA"]: "HISTÓRIA",
  ["TRANSPAR" + R + "`NCIA"]: "TRANSPARÊNCIA",
  ["ATUALIZA" + R + "!" + R + "\"ES"]: "ATUALIZAÇÕES",
  ["D" + R + "aVIDAS"]: "DÚVIDAS",
  ["M" + R + "0DICO"]: "MÉDICO",
  ["CIR" + R + "aRGICO"]: "CIRÚRGICO",
  ["PR" + R + " XIMO"]: "PRÓXIMO",
  ["CÒES"]: "CÃES",
  ["RA" + R + "!ÒO"]: "RAÇÃO",
  ["RA" + R + "!A"]: "RAÇA",
  ["NEGÒO"]: "NEGÃO",
  ["VOV" + R + " "]: "VOVÔ",
  ["SERVI" + R + "!OS"]: "SERVIÇOS",
  ["OPERA" + R + "!ÒO"]: "OPERAÇÃO",
  ["AUTORIZA" + R + "!ÒO"]: "AUTORIZAÇÃO",
  ["COBRAN" + R + "!A"]: "COBRANÇA",
  ["IND" + R + "aSTRIA"]: "INDÚSTRIA",
  ["TIET" + R + "`"]: "TIETÊ",
  ["GALPÒO"]: "GALPÃO",
  ["ELETR" + R + " NICA"]: "ELETRÔNICA",
  ["S" + R + "0RIE"]: "SÉRIE",
  ["AP" + R + " S"]: "APÓS",
  ["AT" + R + "0"]: "ATÉ",
  ["C" + R + " DIGO"]: "CÓDIGO",
  ["DESCRI" + R + "!ÒO"]: "DESCRIÇÃO",
  ["SERVI" + R + "!O"]: "SERVIÇO",
  ["ABSOR" + R + "!ÒO"]: "ABSORÇÃO",
  ["INTERNA" + R + "!" + R + "\"ES"]: "INTERNAÇÕES",
  ["EMERG" + R + "`NCIA"]: "EMERGÊNCIA",
  ["DOA" + R + "!ÒO"]: "DOAÇÃO",
  ["ASSOCIA" + R + "!ÒO"]: "ASSOCIAÇÃO",
  ["PROTE" + R + "!ÒO"]: "PROTEÇÃO",
  [R + "0"]: "É",
  ["voc" + R + "`"]: "você",
  ["Voc" + R + "`"]: "Você",
  ["VOC" + R + "`"]: "VOCÊ",
  [R + "S" + R + "\""]: "✕",
  [R + "S" + R + " "]: "✓",
  [R + "&"]: "⭐",
  [R + "xa" + R]: "🚨",
  [R + "x" + R + "\""]: "📦",
  [R + "x" + R + "   "]: "",
  [R + "x" + R + " a "]: "",
  [R + "a" + R + " ️ "]: "",
  [R + "x}" + R]: "",
  [R + "x" + R + " ` "]: "",
  [R + "x" + R + "  "]: "",
  [R + "  "]: "",
  [R + " " + R]: "❮",
  [R + "x:️"]: "🔒",
  [R + "S  "]: "✔",
  ["A HIST" + R + " RIA"]: "A HISTÓRIA",
  ["HIST" + R + " RIAS"]: "HISTÓRIAS",
  ["c" + R + "ezinhos"]: "cãezinhos",
  ["C" + R + "ezinhos"]: "Cãezinhos",
  ["doadores"]: "doadores",
  ["ra" + R + "!Òo"]: "ração",
  ["FA" + R + "!A"]: "FAÇA",
  ["DOA" + R + "!ÒO"]: "DOAÇÃO",
  ["m" + R + "s"]: "mês",
  ["tr" + R + "s"]: "três"
};
for (const [bad, good] of Object.entries(map)) {
  html = html.split(bad).join(good);
}
fs.writeFileSync("index.html", html, "utf8");
console.log("Fixed with unicode via file.");

